// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace workForum.Models;

public partial class Article
{
    [Key]
    public int A_Id { get; set; }

    [Required]
    [StringLength(50)]
    [DisplayName("標題")]
    public string Title { get; set; }

    [Required]
    [StringLength(50)]
    [DisplayName("上傳圖片")]
    public string FileNAme { get; set; }

    [Required]
    [DisplayName("內文")]
    public string Content { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    [DisplayName("發文者")]
    public string Account { get; set; }
    [DisplayName("發布時間")]

    [Column(TypeName = "datetime")]
    public DateTime CreateTime { get; set; }
    [DisplayName("瀏覽次數")]
    public int Watch { get; set; }

    
        
    

}