// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace workForum.Models;

public partial class Member
{
    [Key]
    [StringLength(30)]
    [Unicode(false)]
    [DisplayName("帳號")]
    public string Account { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("密碼")]
    public string Password { get; set; }

    [Required]
    [StringLength(20)]
    [DisplayName("姓名")]
    public string Name { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    [DisplayName("信箱")]
    public string Email { get; set; }

    [Required]
    [StringLength(10)]
    [DisplayName("信箱驗證碼")]
    public string AuthCode { get; set; }
    [DisplayName("是否為管理者")]

    public bool IsAdmin { get; set; }
}