// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace workForum.Models;

public partial class workForumContext : DbContext
{
    public workForumContext(DbContextOptions<workForumContext> options)
        : base(options)
    {
    }
    public workForumContext()  //預設建構子
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseSqlServer("Server=.\\SQLExpress;Database= workForum;Trusted_Connection=True;TrustServerCertificate=true;MultipleActiveResultSets=true;");
        }
    }
    public virtual DbSet<Album> Album { get; set; }

    public virtual DbSet<Article> Article { get; set; }

    public virtual DbSet<Member> Member { get; set; }

    public virtual DbSet<Message> Message { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Album>(entity =>
        {
            entity.Property(e => e.Account).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.FileName).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Type).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Url).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<Article>(entity =>
        {
            entity.Property(e => e.Account).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Content).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Title).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.Property(e => e.Account).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.AuthCode)
                .IsFixedLength()
                .UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Email).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Name).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Password).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.Property(e => e.Account).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Content).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}